version: '3.8'

services:
  game-engine:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - PORT=8080
      - FIGHTS_PER_TICK=${FIGHTS_PER_TICK:-1200}
      - TICK_INTERVAL_MS=${TICK_INTERVAL_MS:-15}
      - DATABASE_URL=${DATABASE_URL}
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8080/api/round/state"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
